### ISSUE TITLE
CI integration tests fail on Node 10

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/cloud-profiler-nodejs#212] opened 2018-05-24 15:15 UTC
```
Thu May 24 06:07:12 UTC 2018: + npm install /cloud-profiler-nodejs/google-cloud-profiler-0.1.14.tgz
Thu May 24 06:07:19 UTC 2018: In file included from ../../../nan/nan.h:51:0,
Thu May 24 06:07:19 UTC 2018: from ../bindings/sampling-heap-profiler.cc:19:
Thu May 24 06:07:19 UTC 2018: /root/.node-gyp/10.2.0/include/node/node.h:53:50: fatal error: core.h: No such file or directory
Thu May 24 06:07:19 UTC 2018: #include "core.h"  // NOLINT(build/include_order)
Thu May 24 06:07:19 UTC 2018: ^
Thu May 24 06:07:19 UTC 2018: compilation terminated.
Thu May 24 06:07:19 UTC 2018: make: *** [Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o] Error 1
Thu May 24 06:07:19 UTC 2018: gyp ERR! build error
Thu May 24 06:07:19 UTC 2018: gyp ERR! stack Error: `make` failed with exit code: 2
Thu May 24 06:07:19 UTC 2018: gyp ERR! stack     at ChildProcess.onExit (/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
Thu May 24 06:07:19 UTC 2018: gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
Thu May 24 06:07:19 UTC 2018: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
Thu May 24 06:07:19 UTC 2018: gyp ERR! System Linux 4.9.0-6-amd64
Thu May 24 06:07:19 UTC 2018: gyp ERR! command "/.nvm/versions/node/v10.2.0/bin/node" "/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Thu May 24 06:07:19 UTC 2018: gyp ERR! cwd /test/node_modules/@google-cloud/profiler
Thu May 24 06:07:19 UTC 2018: gyp ERR! node -v v10.2.0
Thu May 24 06:07:19 UTC 2018: gyp ERR! node-gyp -v v3.6.2
Thu May 24 06:07:19 UTC 2018: gyp ERR! not ok
```

**Comment by nolanmar511** [comment] 2018-05-24 21:38
I think there was a bug with 10.2.0.
I was able to reproduce locally with 10.2.0 by running `node-gyp rebuild`, but with 10.2.1, this command completed without errors. 
Triggered another build (since the last CI integration test was with 10.2.0). Will close this if the has a successful build with node 10.

**Comment by nolanmar511** [comment] 2018-05-24 21:56
Has a successful CI integration test with node 10.2.1

**Closed by nolanmar511** 2018-05-24 21:56 UTC
Labels: bug

**Comment by ofrobots** [comment] 2018-05-24 23:43
Yep: this was a regression in 10.2.0 :( ([CHANGELOG](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-05-24-version-1021-current-mylesborins))
